# Generated by Django 3.0.8 on 2020-09-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200922_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='timeChoices',
            field=models.CharField(choices=[('15', '15 Minutes'), ('30', '30 Mintues'), ('45', '45 Minutes'), ('60', '1 Hour'), ('90', '1 Hour 30 Minutes'), ('120', '2 hours')], max_length=10),
        ),
    ]
